name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform: [macOS-10.14]
        xcode: [11.3]

    runs-on: ${{ matrix.platform }}
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer

    steps:
      - uses: actions/checkout@v1

      - name: Print Xcode version
        run: xcodebuild -version -sdk

      - name: Test
        run: xcodebuild -project TraktKit.xcodeproj -scheme TraktKit test ENABLE_HARDENED_RUNTIME=NO CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY=
